name: Tests

on: push

jobs:
  release:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm build --if-present
      - run: npm test