name: Tests

on: push

jobs:
  release:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install -g @angular/cli
      - run: npm ci
      - run: npm ci
        working-directory: ./projects/ngx-resgrid-apps-shared
      - run: npm build --if-present
        working-directory: ./projects/ngx-resgrid-apps-shared
      - run: npm run testci
        working-directory: ./projects/ngx-resgrid-apps-shared
